// Package interfaces provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.1 DO NOT EDIT.
package interfaces

import (
	"time"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Order defines model for Order.
type Order struct {
	// 用户创建时间
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// 订单子项
	Items *[]OrderItem `json:"items,omitempty"`

	// 订单唯一标识
	OrderId *string `json:"order_id,omitempty"`

	// 收件人地址信息
	ShippingAddress *ShippingAddress `json:"shipping_address,omitempty"`

	// 用户更新时间
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// OrderItem defines model for OrderItem.
type OrderItem struct {
	// 商品属性集合
	Attributes *[]string `json:"attributes,omitempty"`

	// 商品条码
	Barcode *string `json:"barcode,omitempty"`

	// 商品中文申报名
	DeclaredCnName *string `json:"declared_cn_name,omitempty"`

	// 商品英文申报名
	DeclaredEnName *string `json:"declared_en_name,omitempty"`

	// 商品欧元价值
	DeclaredValueInEur *float32 `json:"declared_value_in_eur,omitempty"`

	// 商品美元价值
	DeclaredValueInUsd *float32 `json:"declared_value_in_usd,omitempty"`

	// 商品高度 (mm)
	Height *float32 `json:"height,omitempty"`

	// 商品海关编码
	HsCode *string `json:"hs_code,omitempty"`

	// 商品长度 (mm)
	Length *float32 `json:"length,omitempty"`

	// 商品名称
	Name *string `json:"name,omitempty"`

	// 商品数量
	Quantity *int `json:"quantity,omitempty"`

	// 商品销售价格
	SellingPrice *float32 `json:"selling_price,omitempty"`

	// 商品SKU
	Sku *string `json:"sku,omitempty"`

	// 商品重量（g)
	Weight *float32 `json:"weight,omitempty"`

	// 商品宽度 (mm)
	Width *float32 `json:"width,omitempty"`
}

// 收件人地址信息
type ShippingAddress struct {
	// 收件人地址
	AddressLine1 *string `json:"address_line1,omitempty"`

	// 收件人地址2
	AddressLine2 *string `json:"address_line2,omitempty"`

	// 收件人城市
	CityName *string `json:"city_name,omitempty"`

	// 收件人国家代码
	CountryCode *string `json:"country_code,omitempty"`

	// 收件人国家
	CountryName *string `json:"country_name,omitempty"`

	// 收件人姓
	FirstName *string `json:"first_name,omitempty"`

	// 收件人名
	LastName *string `json:"last_name,omitempty"`

	// 收件人电话
	PhoneNumber *string `json:"phone_number,omitempty"`

	// 收件人邮编
	PostalCode *string `json:"postal_code,omitempty"`

	// 收件人省份代码
	StateCode *string `json:"state_code,omitempty"`

	// 收件人省份
	StateName *string `json:"state_name,omitempty"`
}

// GetOrdersParams defines parameters for GetOrders.
type GetOrdersParams struct {
	// 订单状态
	Status *interface{} `json:"status,omitempty"`
}
