// Package interfaces provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.1 DO NOT EDIT.
package interfaces

import (
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for GuideInfoRespDataStepsStatus.
const (
	GuideInfoRespDataStepsStatusComplete GuideInfoRespDataStepsStatus = "complete"

	GuideInfoRespDataStepsStatusIncomplete GuideInfoRespDataStepsStatus = "incomplete"
)

// Defines values for GuideInfoRespDataStepsTitle.
const (
	GuideInfoRespDataStepsTitleInfo GuideInfoRespDataStepsTitle = "info"

	GuideInfoRespDataStepsTitleIntegration GuideInfoRespDataStepsTitle = "integration"

	GuideInfoRespDataStepsTitleSignup GuideInfoRespDataStepsTitle = "signup"
)

// Defines values for QuestionTitle.
const (
	QuestionTitleBusinessPlatforms QuestionTitle = "business_platforms"

	QuestionTitleBusinessStage QuestionTitle = "business_stage"

	QuestionTitleProductCategories QuestionTitle = "product_categories"

	QuestionTitleRequiredServices QuestionTitle = "required_services"

	QuestionTitleTargetMarkets QuestionTitle = "target_markets"

	QuestionTitleWebsite QuestionTitle = "website"
)

// CheckEmailReq defines model for CheckEmailReq.
type CheckEmailReq struct {
	// 用户邮箱
	Email openapi_types.Email `json:"email"`
}

// CheckEmailResp defines model for CheckEmailResp.
type CheckEmailResp struct {
	// code
	Code int `json:"code"`

	// message
	Message string `json:"message"`
}

// ForgotPasswordReq defines model for ForgotPasswordReq.
type ForgotPasswordReq struct {
	// 用户邮箱
	Email openapi_types.Email `json:"email"`
}

// ForgotPasswordResp defines model for ForgotPasswordResp.
type ForgotPasswordResp struct {
	// code
	Code int `json:"code"`

	// message
	Message string `json:"message"`
}

// GuideInfoResp defines model for GuideInfoResp.
type GuideInfoResp struct {
	// code
	Code int `json:"code"`
	Data struct {
		// 是否完成新手指引
		Finished bool `json:"finished"`

		// 完善信息的问题
		Questions []Question `json:"questions"`

		// 完善信息的检查项 * signup - 注册完成 * info - 完善信息 * integration - 集成店铺
		Steps []struct {
			// 检查项状态
			Status GuideInfoRespDataStepsStatus `json:"status"`

			// 检查项所在步骤
			Step int `json:"step"`

			// 检查项标题
			Title GuideInfoRespDataStepsTitle `json:"title"`
		} `json:"steps"`
	} `json:"data"`

	// message
	Message string `json:"message"`
}

// 检查项状态
type GuideInfoRespDataStepsStatus string

// 检查项标题
type GuideInfoRespDataStepsTitle string

// LinkStoreReq defines model for LinkStoreReq.
type LinkStoreReq struct {
	// 关联店铺编码
	StoreCode string `json:"store_code"`

	// 用户 ID
	UserId int64 `json:"user_id"`
}

// LinkStoreResp defines model for LinkStoreResp.
type LinkStoreResp struct {
	// code
	Code int                    `json:"code"`
	Data map[string]interface{} `json:"data"`

	// message
	Message string `json:"message"`
}

// LoginReq defines model for LoginReq.
type LoginReq struct {
	// 用户邮箱
	Email openapi_types.Email `json:"email"`

	// 用户密码
	Password string `json:"password"`

	// 关联店铺编码
	StoreCode *string `json:"store_code,omitempty"`
}

// ModifyPasswordReq defines model for ModifyPasswordReq.
type ModifyPasswordReq struct {
	// 用户旧密码
	OldPassword string `json:"old_password"`

	// 新密码
	Password string `json:"password"`
}

// ModifyPasswordResp defines model for ModifyPasswordResp.
type ModifyPasswordResp struct {
	// code
	Code int `json:"code"`

	// message
	Message string `json:"message"`
}

// Question defines model for Question.
type Question struct {
	// 问题答案
	Answer interface{} `json:"answer"`

	// 问题标题
	Title QuestionTitle `json:"title"`
}

// 问题标题
type QuestionTitle string

// SignupReq defines model for SignupReq.
type SignupReq struct {
	// 用户店铺所在平台
	BusinessPlatform *string `json:"business_platform,omitempty"`

	// 用户关心的问题
	Concerns *string `json:"concerns,omitempty"`

	// 用户注册邮箱
	Email openapi_types.Email `json:"email"`

	// 用户注册密码
	Password string `json:"password"`

	// 用户手机号
	Phone string `json:"phone"`

	// 推荐人 ID
	Referrer *int `json:"referrer,omitempty"`

	// 用户注册来源
	Source *string `json:"source,omitempty"`

	// 用户注册来源标签
	SourceTag *string `json:"source_tag,omitempty"`

	// 关联店铺编码
	StoreCode *string `json:"store_code,omitempty"`

	// 用户名
	Username string `json:"username"`

	// 用户店铺链接
	Website *string `json:"website,omitempty"`
}

// TokenResp defines model for TokenResp.
type TokenResp struct {
	// code
	Code int `json:"code"`
	Data struct {
		Token *string `json:"token,omitempty"`
	} `json:"data"`

	// message
	Message string `json:"message"`
}

// UpdateGuideInfoReq defines model for UpdateGuideInfoReq.
type UpdateGuideInfoReq struct {
	// 完善信息的问题
	Questions *[]Question `json:"questions,omitempty"`

	// 是否跳过集成店铺
	SkipIntegration *bool `json:"skip_integration,omitempty"`
}

// UserInfo defines model for UserInfo.
type UserInfo struct {
	// 用户邮箱
	Email string `json:"email"`

	// 是否完成新手指引
	GuideFinished bool `json:"guide_finished"`

	// 电话
	Phone string `json:"phone"`

	// 用户 ID
	UserId int64 `json:"user_id"`

	// 用户名
	Username string `json:"username"`
}

// UserInfoResp defines model for UserInfoResp.
type UserInfoResp struct {
	// code
	Code int      `json:"code"`
	Data UserInfo `json:"data"`

	// message
	Message string `json:"message"`
}

// CheckEmailJSONBody defines parameters for CheckEmail.
type CheckEmailJSONBody CheckEmailReq

// ForgotPasswordJSONBody defines parameters for ForgotPassword.
type ForgotPasswordJSONBody ForgotPasswordReq

// UpdateGuideInfoJSONBody defines parameters for UpdateGuideInfo.
type UpdateGuideInfoJSONBody UpdateGuideInfoReq

// LinkStoreJSONBody defines parameters for LinkStore.
type LinkStoreJSONBody LinkStoreReq

// LoginJSONBody defines parameters for Login.
type LoginJSONBody LoginReq

// ModifyPasswordJSONBody defines parameters for ModifyPassword.
type ModifyPasswordJSONBody ModifyPasswordReq

// SignupJSONBody defines parameters for Signup.
type SignupJSONBody SignupReq

// CheckEmailJSONRequestBody defines body for CheckEmail for application/json ContentType.
type CheckEmailJSONRequestBody CheckEmailJSONBody

// ForgotPasswordJSONRequestBody defines body for ForgotPassword for application/json ContentType.
type ForgotPasswordJSONRequestBody ForgotPasswordJSONBody

// UpdateGuideInfoJSONRequestBody defines body for UpdateGuideInfo for application/json ContentType.
type UpdateGuideInfoJSONRequestBody UpdateGuideInfoJSONBody

// LinkStoreJSONRequestBody defines body for LinkStore for application/json ContentType.
type LinkStoreJSONRequestBody LinkStoreJSONBody

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody LoginJSONBody

// ModifyPasswordJSONRequestBody defines body for ModifyPassword for application/json ContentType.
type ModifyPasswordJSONRequestBody ModifyPasswordJSONBody

// SignupJSONRequestBody defines body for Signup for application/json ContentType.
type SignupJSONRequestBody SignupJSONBody
