// Package interfaces provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.1 DO NOT EDIT.
package interfaces

import (
	"time"
)

// Resp defines model for Resp.
type Resp struct {
	Service string `json:"service"`
	Status  string `json:"status"`

	// 当前时间
	Timestamp time.Time `json:"timestamp"`
}
